{% set name = "coverage-badge" %}
{% set version = "1.1.2" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fe7ed58a3b72dad85a553b64a99e963dea3847dcd0b8ddd2b38a00333618642c

build:
  number: 0
  noarch: python
  entry_points:
    - coverage-badge = coverage_badge.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
    - coverage

test:
  requires:
    - python {{ python_min }}
  imports:
    - coverage_badge
  commands:
    - coverage-badge --help

about:
  home: https://github.com/dbrgn/coverage-badge
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Generate coverage badges for Coverage.py.
  dev_url: https://github.com/dbrgn/coverage-badge

extra:
  recipe-maintainers:
    - Hoxbro
